# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e2bfd378d1fce12499fd7e50b5c21c81"
name = "test-ds-app"
handle = "test-ds-app"
application_url = "https://aa9518ecf61e.ngrok-free.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_customers,read_products"

[auth]
redirect_urls = ["https://aa9518ecf61e.ngrok-free.app/auth/callback", "https://aa9518ecf61e.ngrok-free.app/auth/shopify/callback", "https://aa9518ecf61e.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false
